language: node_js
node_js:
  - "6"
  - "7"
  - "8"
cache:
  directories:
    - node_modules
script:
  - yarn run eslint js/** --config config/eslint.config.js
  - yarn run stylelint scss/**/*.scss --config config/stylelint.config.js
  - yarn run flow
  - yarn run jest --config config/jest.config.js